apiVersion: 1
datasources:
  - name: Tempo
    uid: Tempo
    type: tempo
    url: http://tempo:3200
    isDefault: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: Loki
        spanStartTimeShift: "-1m"
        spanEndTimeShift: "1m"
        filterByTraceID: true
        customQuery: true
        query: '{service_name="$${__span.tags["service.name"]}"} | json | trace_id = "$${__trace.traceId}"'
      lokiSearch:
        datasourceUid: Loki
